# Module 2: Exercise (Solution)

>__Task 1__
>
>Import pandas and NumPy libraries using their alias

In [1]:
import pandas as pd
import numpy as np

## Python Native Data Types

### Numbers, Strings, Booleans

>__Task 2__
>
>Perform the following operations and return to see the results
>- $3+2\times4$
>- $(3+2)\div4$
>- $(3+2)^4$
>- get the integer quotient of $(3+2)/4$ using floor division

In [2]:
3+2*4

11

In [3]:
(3+2)/4

1.25

In [4]:
(3+2)**4

625

In [5]:
(3+2)//4

1

Note __the floor division rounds the result to the nearest whole number__.

>__Task 3__
>
>Run the following cells and find the data type of each object

In [6]:
4//7

0

In [7]:
# Return data type
type(4//7)

int

In [8]:
a = 11/(-3)
a

-3.6666666666666665

In [9]:
# Return data type
type(a)

float

In [10]:
b = True
# Return data type
type(b)

bool

>__Task 4__
>
>Assume your student ID is 00223298, assign it to a variable as a string object

In [11]:
id = '00223298'
# Return data type
type(id)

str

>__Task 5__
>
>Convert the variable __c__ below to float

In [12]:
c = '6.0'
# Convert to float
c = float(c)
c

6.0

In [13]:
# Return data type
type(c)

float

>__Task 6__
>
>Run the cell below to get the value of variable __d__ and then convert it to integer

In [14]:
d = (-6) < 78
d

True

In [15]:
# Convert to integer
d = int(d)
d

1

In [16]:
# Return data type
type(d)

int

### Lists, Tuples, Sets

>__Task 7__
>
>Create a list, a tuple, and a set containing the following elements and compare the outputs:
>
>`0`, `robot` (str), `-9`, `False` (bool), `77`, `77`, `100`, `true` (str)

In [17]:
# Create a list
# l = list((0, 'robot', -9, False, 77, 77, 100, 'true'))
# OR
l = [0, 'robot', -9, False, 77, 77, 100, 'true']
l

[0, 'robot', -9, False, 77, 77, 100, 'true']

In [18]:
# Return data type
type(l)

list

In [19]:
# Create a tuple
# t = tuple((0, 'robot', -9, False, 77, 77, 100, 'true'))
# OR
t = (0, 'robot', -9, False, 77, 77, 100, 'true')
t

(0, 'robot', -9, False, 77, 77, 100, 'true')

In [20]:
# Return data type
type(t)

tuple

In [21]:
# Create a set
# s = set((0, 'robot', -9, False, 77, 77, 100, 'true'))
# OR
s = {0, 'robot', -9, False, 77, 77, 100, 'true'}
s

{-9, 0, 100, 77, 'robot', 'true'}

In [22]:
# Return data type
type(s)

set

>__Task 8__
>
>Overwrite the element `true` to `1` in the above list __l__

In [23]:
# l[7] = 1
# OR
l[-1] = 1
l

[0, 'robot', -9, False, 77, 77, 100, 1]

>__Task 9__
>
>Add `age` and `weight` to the list __e__ below using __`+`__

In [24]:
e = ['diabetes', 'heart bypass']
e

['diabetes', 'heart bypass']

In [25]:
f = e + ['age', 'weight']
f

['diabetes', 'heart bypass', 'age', 'weight']

Alternatively, you can use the __`extend()`__ method to add item(s) to the end of the list:

In [26]:
e.extend(['age', 'weight'])
e

['diabetes', 'heart bypass', 'age', 'weight']

### Dictionaries

In [27]:
cities = {'Australia' :['Sydney', 'Melbourne', 'Canberra'],
          'Canada'    :['Toronto', 'Montreal', 'Ottawa'],
          'Germany'   :['Berlin', 'Hamburg', 'Munich'],
          'Japan'     :['Tokyo', 'Osaka', 'Nagoya']}
cities

{'Australia': ['Sydney', 'Melbourne', 'Canberra'],
 'Canada': ['Toronto', 'Montreal', 'Ottawa'],
 'Germany': ['Berlin', 'Hamburg', 'Munich'],
 'Japan': ['Tokyo', 'Osaka', 'Nagoya']}

>__Task 10__
>
>Return only values of the `Japan` key

In [28]:
cities['Japan']

['Tokyo', 'Osaka', 'Nagoya']

>__Task 11__
>
>Return only values and only keys of the dictionary __cities__

In [29]:
# Return only values
cities.values()

dict_values([['Sydney', 'Melbourne', 'Canberra'], ['Toronto', 'Montreal', 'Ottawa'], ['Berlin', 'Hamburg', 'Munich'], ['Tokyo', 'Osaka', 'Nagoya']])

In [30]:
# Return only keys
cities.keys()

dict_keys(['Australia', 'Canada', 'Germany', 'Japan'])

You can use a __`for`__ loop to print not only keys but also the values corresponding to that keys:

In [31]:
for k in cities.keys():
    print('key: ', k, '\nvalue: ', cities[k], '\n')

key:  Australia 
value:  ['Sydney', 'Melbourne', 'Canberra'] 

key:  Canada 
value:  ['Toronto', 'Montreal', 'Ottawa'] 

key:  Germany 
value:  ['Berlin', 'Hamburg', 'Munich'] 

key:  Japan 
value:  ['Tokyo', 'Osaka', 'Nagoya'] 



>__Task 12__
>
>Return the same output above using the __`items()`__ method within a `for` loop

In [32]:
for k,v in cities.items():
    print('key: ', k, '\nvalue: ', v, '\n')

key:  Australia 
value:  ['Sydney', 'Melbourne', 'Canberra'] 

key:  Canada 
value:  ['Toronto', 'Montreal', 'Ottawa'] 

key:  Germany 
value:  ['Berlin', 'Hamburg', 'Munich'] 

key:  Japan 
value:  ['Tokyo', 'Osaka', 'Nagoya'] 



>__Task 13__
>
>Add `Egypt` as a new key to __cities__ and `Cairo`, `Durban`, `Alexandria` as its corresponding values

In [33]:
cities['Egypt'] = ['Cairo', 'Durban', 'Alexandria']
cities

{'Australia': ['Sydney', 'Melbourne', 'Canberra'],
 'Canada': ['Toronto', 'Montreal', 'Ottawa'],
 'Germany': ['Berlin', 'Hamburg', 'Munich'],
 'Japan': ['Tokyo', 'Osaka', 'Nagoya'],
 'Egypt': ['Cairo', 'Durban', 'Alexandria']}

>__Task 14__
>
>`Durban` is actually in South Africa. Overwrite it with `Giza`

In [34]:
cities['Egypt'][1] = 'Giza'
cities['Egypt']

['Cairo', 'Giza', 'Alexandria']

>__Task 15__
>
>Delete the key `Germany` from __cities__ 

In [35]:
del cities['Germany']
cities

{'Australia': ['Sydney', 'Melbourne', 'Canberra'],
 'Canada': ['Toronto', 'Montreal', 'Ottawa'],
 'Japan': ['Tokyo', 'Osaka', 'Nagoya'],
 'Egypt': ['Cairo', 'Giza', 'Alexandria']}

## NumPy Arrays

>__Task 16__
>
>Create an array that contains a list of `99`, `2`, `65`

In [36]:
arr = np.array([99, 2, 65])
arr

array([99,  2, 65])

>__Task 17__
>
>Run the following operations to see the results

In [37]:
# Natural logarithm
np.log(arr)

array([4.59511985, 0.69314718, 4.17438727])

In [38]:
# Square root
np.sqrt(arr)

array([9.94987437, 1.41421356, 8.06225775])

In [39]:
# Cosine
np.cos(arr)

array([ 0.03982088, -0.41614684, -0.56245385])

We can use the __`arange()`__ method to create an array from 0 to any number of values we want. For example, we want an array of 20 numbers, we write:

In [40]:
num1 = np.arange(20)
num1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

>__Task 18__
>
>Retrieve the first 5 numbers of the above array __num1__

In [41]:
num1[:5]

array([0, 1, 2, 3, 4])

We can also pass the __`reshape()`__ function with `arange()` to specify rows and columns. For example, we can rearrange the above array into 5 rows and 4 columns:

In [42]:
num2 = np.arange(20).reshape(5,4)
num2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

>__Task 19__
>
>Retrieve the numbers from the last 2 rows and first 3 columns in the array __num2__ (your output should return `[12, 13, 14], [16, 17, 18]`)

In [43]:
# num2[3:,:3]
# OR
num2[-2:,:3]

array([[12, 13, 14],
       [16, 17, 18]])

## Pandas Series and DataFrames

>__Task 20__
>
>Import the data file "bank_data.csv"

In [44]:
bank = pd.read_csv('bank_data.csv')
bank

age            job  marital  education default  balance housing loan  \
0     30.0     unemployed  married    primary      no   1787.0      no   no   
1     33.0       services  married  secondary      no   4789.0     yes  yes   
2     35.0     management   single   tertiary      no   1350.0     yes   no   
3     30.0     management  married   tertiary      no      NaN     yes  yes   
4     59.0    blue-collar  married  secondary      no      0.0     yes   no   
...    ...            ...      ...        ...     ...      ...     ...  ...   
4516  33.0       services  married  secondary      no   -333.0     yes   no   
4517  57.0  self-employed  married   tertiary     yes  -3313.0     yes  yes   
4518  57.0     technician  married  secondary      no    295.0      no   no   
4519  28.0    blue-collar  married  secondary      no   1137.0      no   no   
4520  44.0   entrepreneur   single   tertiary      no   1136.0     yes  yes   

       contact   day  month  duration  campaign  pdays  previous poutcome   y  \
0     cellular  19.0     10      79.0       1.0   -1.0       0.0  unknown  no   
1     cellular  11.0      5     220.0       1.0  339.0       4.0  failure  no   
2     cellular  16.0      4     185.0       1.0  330.0       1.0  failure  no   
3          NaN   3.0      6     199.0       4.0   -1.0       0.0  unknown  no   
4          NaN   5.0      5     226.0       1.0   -1.0       0.0  unknown  no   
...        ...   ...    ...       ...       ...    ...       ...      ...  ..   
4516  cellular  30.0      7     329.0       5.0   -1.0       0.0  unknown  no   
4517       NaN   9.0      5     153.0       1.0   -1.0       0.0  unknown  no   
4518  cellular  19.0      8     151.0      11.0   -1.0       0.0  unknown  no   
4519  cellular   6.0      2     129.0       4.0  211.0       3.0    other  no   
4520  cellular   3.0      4     345.0       2.0  249.0       7.0    other  no   

      year  
0     2022  
1     2022  
2     2022  
3     2022  
4     2022  
...    ...  
4516  2022  
4517  2022  
4518  2022  
4519  2022  
4520  2022  

[4521 rows x 18 columns]

>__Task 21__
>
>Select __age__ column as a series and confirm the result by checking its data type

In [45]:
bank['age']

0       30.0
1       33.0
2       35.0
3       30.0
4       59.0
        ... 
4516    33.0
4517    57.0
4518    57.0
4519    28.0
4520    44.0
Name: age, Length: 4521, dtype: float64

In [46]:
# Return data type
type(bank['age'])

pandas.core.series.Series

Notice that __`df[...]` returns a series and `df[[...]]` returns a data frame__.

>__Task 22__
>
>Select columns __job__, __education__, and __balance__ as a data frame and confirm the result by checking its data type

In [47]:
bank[['job','education','balance']]

job  education  balance
0        unemployed    primary   1787.0
1          services  secondary   4789.0
2        management   tertiary   1350.0
3        management   tertiary      NaN
4       blue-collar  secondary      0.0
...             ...        ...      ...
4516       services  secondary   -333.0
4517  self-employed   tertiary  -3313.0
4518     technician  secondary    295.0
4519    blue-collar  secondary   1137.0
4520   entrepreneur   tertiary   1136.0

[4521 rows x 3 columns]

In [48]:
# Return data type
type(bank[['job','education','balance']])

pandas.core.frame.DataFrame

>__Task 23__
>
>Retrieve the last 7 rows and first 5 columns from the __bank__ data

In [49]:
bank.iloc[-7:,:5]

age            job  marital  education default
4514  38.0    blue-collar  married  secondary      no
4515  32.0       services   single  secondary      no
4516  33.0       services  married  secondary      no
4517  57.0  self-employed  married   tertiary     yes
4518  57.0     technician  married  secondary      no
4519  28.0    blue-collar  married  secondary      no
4520  44.0   entrepreneur   single   tertiary      no

### Dates and Times

Let's create a new column of the client contact dates using the __bank__ data:

In [50]:
bank['contact_date'] = bank['year'].astype(str)+'-'+bank['month'].astype(str)+'-'+bank['day'].astype(int).astype(str)
bank['contact_date']

0       2022-10-19
1        2022-5-11
2        2022-4-16
3         2022-6-3
4         2022-5-5
           ...    
4516     2022-7-30
4517      2022-5-9
4518     2022-8-19
4519      2022-2-6
4520      2022-4-3
Name: contact_date, Length: 4521, dtype: object

The last line above shows that the dtype (data type) is a generic object, not a datetime type.

>__Task 24__
>
>Convert the __contact_date__ column to a datetime object

In [51]:
bank['contact_date'] = pd.to_datetime(bank['contact_date'])
bank['contact_date']

0      2022-10-19
1      2022-05-11
2      2022-04-16
3      2022-06-03
4      2022-05-05
          ...    
4516   2022-07-30
4517   2022-05-09
4518   2022-08-19
4519   2022-02-06
4520   2022-04-03
Name: contact_date, Length: 4521, dtype: datetime64[ns]

Now, it is properly read as date.

## Data Manipulation

In [52]:
import warnings
warnings.filterwarnings("ignore")

>__Task 25__
>
>Import the data file "hc_train.csv" and explore the first 5 rows

In [53]:
hc = pd.read_csv('hc_train.csv')
hc.head()

Unnamed: 0  case_id  Hospital_code Hospital_type_code  City_Code_Hospital  \
0      119967   119968             27                  a                   7   
1       92433    92434              6                  a                   6   
2      132258   132259             16                  c                   3   
3      168439   168440             23                  a                   6   
4       82100    82101             25                  e                   1   

  Hospital_region_code  Available Extra Rooms in Hospital  Department  \
0                    Y                                  3  gynecology   
1                    X                                  4  gynecology   
2                    Z                                  4  gynecology   
3                    X                                  2  anesthesia   
4                    X                                  3  gynecology   

  Ward_Type Ward_Facility_Code  Bed Grade  patientid  City_Code_Patient  \
0         R                  C        2.0      11389                8.0   
1         Q                  F        1.0      12522                2.0   
2         S                  A        3.0     119556                8.0   
3         S                  F        3.0     107177                8.0   
4         R                  E        3.0      64508               13.0   

  Type of Admission Severity of Illness  Visitors with Patient    Age  \
0         Emergency               Minor                      2  11-20   
1         Emergency             Extreme                      4  31-40   
2            Trauma            Moderate                      6  71-80   
3            Urgent             Extreme                      2  71-80   
4            Trauma            Moderate                      3  61-70   

   Admission_Deposit                Stay  
0             5072.0               21-30  
1             3585.0               21-30  
2             4013.0  More than 100 Days  
3             5160.0               21-30  
4             4099.0               21-30

>__Task 26__
>
>Convert the values of the __Department__ column to uppercase

In [54]:
hc['Department'].str.upper()

0                GYNECOLOGY
1                GYNECOLOGY
2                GYNECOLOGY
3                ANESTHESIA
4                GYNECOLOGY
                ...        
51233            GYNECOLOGY
51234            GYNECOLOGY
51235            GYNECOLOGY
51236            GYNECOLOGY
51237    TB & CHEST DISEASE
Name: Department, Length: 51238, dtype: object

### Replace Values

>__Task 27__
>
>Replace `TB & Chest disease` in the __Department__ column with `Tuberculosis & Chest`

In [55]:
hc['Department'] = hc['Department'].replace('TB & Chest disease','Tuberculosis & Chest')

# Print unique variables in the column to confirm the change 
hc['Department'].unique()

array(['gynecology', 'anesthesia', 'radiotherapy', 'surgery',
       'Tuberculosis & Chest'], dtype=object)

We can also replace with different values by passing a list or dict as substitutes.

>__Task 28__
>
>Replace values in the __Severity of Illness__ column with a dictionary that maps variables below:
>
>- Extreme: '3rd degree'
>- Moderate: '2nd degree'
>- Minor: '1st degree'

In [56]:
# Creat a dict
map_dict = {'Extreme': '3rd degree', 'Moderate': '2nd degree', 'Minor': '1st degree'}
# Replace values with the dict
hc['Severity of Illness'].replace(map_dict)

0        1st degree
1        3rd degree
2        2nd degree
3        3rd degree
4        2nd degree
            ...    
51233    1st degree
51234    2nd degree
51235    2nd degree
51236    1st degree
51237    3rd degree
Name: Severity of Illness, Length: 51238, dtype: object

### Rename Column and Row Labels

>__Task 29__
>
>Rename all column headings to their lowercase values by passing a `str` function

In [57]:
hc.rename(columns=str.lower)

unnamed: 0  case_id  hospital_code hospital_type_code  \
0          119967   119968             27                  a   
1           92433    92434              6                  a   
2          132258   132259             16                  c   
3          168439   168440             23                  a   
4           82100    82101             25                  e   
...           ...      ...            ...                ...   
51233      289419   289420             10                  e   
51234      285283   285284             11                  b   
51235       79117    79118              9                  d   
51236      128901   128902             23                  a   
51237      210970   210971              2                  c   

       city_code_hospital hospital_region_code  \
0                       7                    Y   
1                       6                    X   
2                       3                    Z   
3                       6                    X   
4                       1                    X   
...                   ...                  ...   
51233                   1                    X   
51234                   2                    Y   
51235                   5                    Z   
51236                   6                    X   
51237                   5                    Z   

       available extra rooms in hospital            department ward_type  \
0                                      3            gynecology         R   
1                                      4            gynecology         Q   
2                                      4            gynecology         S   
3                                      2            anesthesia         S   
4                                      3            gynecology         R   
...                                  ...                   ...       ...   
51233                                  3            gynecology         Q   
51234                                  4            gynecology         Q   
51235                                  3            gynecology         S   
51236                                  4            gynecology         R   
51237                                  2  Tuberculosis & Chest         S   

      ward_facility_code  bed grade  patientid  city_code_patient  \
0                      C        2.0      11389                8.0   
1                      F        1.0      12522                2.0   
2                      A        3.0     119556                8.0   
3                      F        3.0     107177                8.0   
4                      E        3.0      64508               13.0   
...                  ...        ...        ...                ...   
51233                  E        4.0      84995                8.0   
51234                  D        2.0      27052                8.0   
51235                  F        3.0     109756                5.0   
51236                  F        4.0      35479               12.0   
51237                  F        2.0      99310                9.0   

      type of admission severity of illness  visitors with patient    age  \
0             Emergency               Minor                      2  11-20   
1             Emergency             Extreme                      4  31-40   
2                Trauma            Moderate                      6  71-80   
3                Urgent             Extreme                      2  71-80   
4                Trauma            Moderate                      3  61-70   
...                 ...                 ...                    ...    ...   
51233            Trauma               Minor                      2  21-30   
51234         Emergency            Moderate                      2  51-60   
51235         Emergency            Moderate                     10  51-60   
51236            Trauma               Minor                      2  21-30   
51237            Trauma             Extreme     

>__Task 30__
>
>Rename the column headings below using a dictionary that maps
>
>- `Severity of Illness` to `Severity`
>- `case_id` to `ID`

In [58]:
col_dict = {'Severity of Illness': 'Severity', 'case_id': 'ID'}
hc.rename(columns=col_dict)

Unnamed: 0      ID  Hospital_code Hospital_type_code  \
0          119967  119968             27                  a   
1           92433   92434              6                  a   
2          132258  132259             16                  c   
3          168439  168440             23                  a   
4           82100   82101             25                  e   
...           ...     ...            ...                ...   
51233      289419  289420             10                  e   
51234      285283  285284             11                  b   
51235       79117   79118              9                  d   
51236      128901  128902             23                  a   
51237      210970  210971              2                  c   

       City_Code_Hospital Hospital_region_code  \
0                       7                    Y   
1                       6                    X   
2                       3                    Z   
3                       6                    X   
4                       1                    X   
...                   ...                  ...   
51233                   1                    X   
51234                   2                    Y   
51235                   5                    Z   
51236                   6                    X   
51237                   5                    Z   

       Available Extra Rooms in Hospital            Department Ward_Type  \
0                                      3            gynecology         R   
1                                      4            gynecology         Q   
2                                      4            gynecology         S   
3                                      2            anesthesia         S   
4                                      3            gynecology         R   
...                                  ...                   ...       ...   
51233                                  3            gynecology         Q   
51234                                  4            gynecology         Q   
51235                                  3            gynecology         S   
51236                                  4            gynecology         R   
51237                                  2  Tuberculosis & Chest         S   

      Ward_Facility_Code  Bed Grade  patientid  City_Code_Patient  \
0                      C        2.0      11389                8.0   
1                      F        1.0      12522                2.0   
2                      A        3.0     119556                8.0   
3                      F        3.0     107177                8.0   
4                      E        3.0      64508               13.0   
...                  ...        ...        ...                ...   
51233                  E        4.0      84995                8.0   
51234                  D        2.0      27052                8.0   
51235                  F        3.0     109756                5.0   
51236                  F        4.0      35479               12.0   
51237                  F        2.0      99310                9.0   

      Type of Admission  Severity  Visitors with Patient    Age  \
0             Emergency     Minor                      2  11-20   
1             Emergency   Extreme                      4  31-40   
2                Trauma  Moderate                      6  71-80   
3                Urgent   Extreme                      2  71-80   
4                Trauma  Moderate                      3  61-70   
...                 ...       ...                    ...    ...   
51233            Trauma     Minor                      2  21-30   
51234         Emergency  Moderate                      2  51-60   
51235         Emergency  Moderate                     10  51-60   
51236            Trauma     Minor                      2  21-30   
51237            Trauma   Extreme                      4  51-60   

       Admission_Deposit                Stay  
0                 5072.0               21-30  
1       

### Binning Methods

>__Task 31__
>
>Group the case IDs into three categories below:
>
>- (0, 100000) to `old case`
>- (100001-200000) to `recent case`
>- (200001-last) to `new case`

In [59]:
# Check the maximum value of the column
hc['case_id'].max()

318438

In [60]:
group = pd.cut(hc['case_id'], [0, 100000, 200000, 318437], labels=['old case','recent case','new case'])
group

0        recent case
1           old case
2        recent case
3        recent case
4           old case
            ...     
51233       new case
51234       new case
51235       old case
51236    recent case
51237       new case
Name: case_id, Length: 51238, dtype: category
Categories (3, object): ['old case' < 'recent case' < 'new case']

>__Task 32__
>
>Group the case IDs into to 3 equal-sized bins with 4 decimal places

In [61]:
group_equ = pd.cut(hc['case_id'], bins=3, precision=4) #bins= can be omitted
group_equ

0        (106146.6667, 212292.3333]
1           (-317.437, 106146.6667]
2        (106146.6667, 212292.3333]
3        (106146.6667, 212292.3333]
4           (-317.437, 106146.6667]
                    ...            
51233       (212292.3333, 318438.0]
51234       (212292.3333, 318438.0]
51235       (-317.437, 106146.6667]
51236    (106146.6667, 212292.3333]
51237    (106146.6667, 212292.3333]
Name: case_id, Length: 51238, dtype: category
Categories (3, interval[float64, right]): [(-317.437, 106146.6667] < (106146.6667, 212292.3333] < (212292.3333, 318438.0]]

>__Task 33__
>
>Group the case IDs into 4 quartiles with 2 decimal places

In [62]:
group_qua = pd.qcut(hc['case_id'], q=4, precision=2) #q= can be omitted
group_qua

0        (79834.25, 159728.5]
1        (79834.25, 159728.5]
2        (79834.25, 159728.5]
3        (159728.5, 238968.5]
4        (79834.25, 159728.5]
                 ...         
51233    (238968.5, 318438.0]
51234    (238968.5, 318438.0]
51235        (0.99, 79834.25]
51236    (79834.25, 159728.5]
51237    (159728.5, 238968.5]
Name: case_id, Length: 51238, dtype: category
Categories (4, interval[float64, right]): [(0.99, 79834.25] < (79834.25, 159728.5] < (159728.5, 238968.5] < (238968.5, 318438.0]]

### Random Sampling

>__Task 34__
>
>Randomly select 10 data points from the __hc__ data without repeat elements

In [63]:
hc.sample(10, replace=False)

Unnamed: 0  case_id  Hospital_code Hospital_type_code  \
3502       166004   166005              2                  c   
27336      216989   216990             19                  a   
20014       97783    97784             27                  a   
10870      214585   214586             15                  c   
40857      161752   161753             13                  a   
45277      277666   277667             24                  a   
25538      132336   132337             15                  c   
8860        64569    64570             29                  a   
16167      206756   206757             31                  c   
46264      296401   296402             15                  c   

       City_Code_Hospital Hospital_region_code  \
3502                    5                    Z   
27336                   7                    Y   
20014                   7                    Y   
10870                   5                    Z   
40857                   5                    Z   
45277                   1                    X   
25538                   5                    Z   
8860                    4                    X   
16167                   3                    Z   
46264                   5                    Z   

       Available Extra Rooms in Hospital  Department Ward_Type  \
3502                                   4  gynecology         Q   
27336                                  2  gynecology         S   
20014                                  4  gynecology         R   
10870                                  2  gynecology         Q   
40857                                  3  gynecology         R   
45277                                  3  gynecology         R   
25538                                  2  gynecology         R   
8860                                   2  gynecology         R   
16167                                  3  gynecology         S   
46264                                  3  gynecology         S   

      Ward_Facility_Code  Bed Grade  patientid  City_Code_Patient  \
3502                   F        1.0     111562                8.0   
27336                  C        4.0      86465                8.0   
20014                  C        2.0     121550                8.0   
10870                  F        3.0      83624               23.0   
40857                  F        2.0      47011                2.0   
45277                  E        2.0     100024                2.0   
25538                  F        3.0      44232                8.0   
8860                   F        4.0      30812                1.0   
16167                  A        3.0      71380                8.0   
46264                  F        4.0     122959                5.0   

      Type of Admission Severity of Illness  Visitors with Patient    Age  \
3502             Trauma             Extreme                      4  41-50   
27336         Emergency               Minor                      2   0-10   
20014            Urgent               Minor                      2  31-40   
10870            Trauma               Minor                      2   0-10   
40857            Trauma            Moderate                      2  31-40   
45277            Trauma            Moderate                      2  31-40   
25538         Emergency            Moderate                      4  51-60   
8860             Urgent            Moderate                      3  41-50   
16167            Trauma               Minor                      2  61-70   
46264            Urgent               Minor                      2  11-20   

       Admission_Deposit   Stay  
3502              3749.0  21-30  
27336             5027.0  11-20  
20014             5109.0  11-20  
10870             5646.0  21-30  
40857             5831.0  11-20  
45277             4624.0  11-20  
25538             5436.0  31-40  
8860              5219.0  11-20  
16167             4825.0  21-30  
46264             5663.0  11-20

>__Task 35__
>
>Randomly select 50 data points from the __patientid__ column allowing repeat elements

In [64]:
hc['patientid'].sample(50, replace=True)

25055    114066
29330    100902
3170      35251
34371     68955
23175    122814
7137     120474
50227     52425
13760     35819
21424     82203
10690     79919
49658     74667
5568      90863
34432     92098
719        1846
34502     42554
3152      41856
19778     29879
24601    102100
46785     80701
44565     29586
50663     85074
1435       8243
5907      20289
25990     58353
42403     85539
5984      30368
23352    123135
4002       2767
51030     63783
47147     11380
30794     72076
691       40589
17921    107893
40382     54926
14702    120068
14622     60827
3474      36601
48218     42150
25416     20192
28951     27400
43906     65996
7635      48912
32325     28031
21871     41720
4259     117355
43696     24687
26264     97603
28707     30926
48539    117076
31098     13058
Name: patientid, dtype: int64