# Module 2: Exercise

>__Task 1__
>
>Import pandas and NumPy libraries using their alias

In [1268]:
import numpy as np


## Python Native Data Types

### Numbers, Strings, Booleans

>__Task 2__
>
>Perform the following operations and return to see the results
>- $3+2\times4$
>- $(3+2)\div4$
>- $(3+2)^4$
>- get the integer quotient of $(3+2)/4$ using floor division

In [1269]:
ans = 3+2*4
ans

11

In [1270]:
(3+2)/4

1.25

In [1271]:
(3+2)**4

625

In [1272]:
(3 + 2) // 4

1

Note __the floor division rounds the result to the nearest whole number__.

>__Task 3__
>
>Run the following cells and find the data type of each object

In [1273]:
ans_task3 = 4//7

In [1274]:
# Return data type
print(type(ans_task3))

<class 'int'>


In [1275]:
a = 11/(-3)
a

-3.6666666666666665

In [1276]:
# Return data type
type(a)  # shows the object type as output of the cell in Jupyter notebook/ any python notebook script. 
# x =type(a)  # Even use like this/.
# print(x)
print(type(a))  # shows the object type as output in terminal or normal script run.

<class 'float'>


In [1277]:
b = True
# Return data type
print(type(b))

<class 'bool'>


>__Task 4__
>
>Assume your student ID is 00223298, assign it to a variable as a string object

In [1278]:
# id = str(00223298)
id = "00223298"
# Return data type
print(type(id))

<class 'str'>


>__Task 5__
>
>Convert the variable __c__ below to float

In [1279]:
c = '6.0'
# Convert to float
c = float(c) # Force conversion from string to float
# c = eval(c) # any data type to their corresponding data type so avoid `eval` unless you 100% trust the input.
c

6.0

In [1280]:
# Return data type
print(type(c))

<class 'float'>


>__Task 6__
>
>Run the cell below to get the value of variable __d__ and then convert it to integer

In [1281]:
d = (-6) < 78
d

True

In [1282]:
# Convert to integer
d = int(d)
d

1

In [1283]:
# Return data type
print(type(d))

<class 'int'>


### Lists, Tuples, Sets

>__Task 7__
>
>Create a list, a tuple, and a set containing the following elements and compare the outputs:
>
>`0`, `robot` (str), `-9`, `False` (bool), `77`, `77`, `100`, `true` (str)

In [1284]:
# Create a list
l = [ 0, 'robot', -9, False, 77,77,100, 'true']
l

[0, 'robot', -9, False, 77, 77, 100, 'true']

In [1285]:
# Return data type
print(type(l))

<class 'list'>


In [1286]:
# Create a tuple
# t = (0, 'robot', -9, False, 77,77,100, 'true')
t = tuple(l)
t

(0, 'robot', -9, False, 77, 77, 100, 'true')

In [1287]:
# Return data type
print(type(t))

<class 'tuple'>


In [1288]:
# Create a set
s = {0, 'robot', -9, False, 77,77,100, 'true'}
# s = set(l)
s

{-9, 0, 100, 77, 'robot', 'true'}

In [1289]:
# Return data type
print(type(s))

<class 'set'>


>__Task 8__
>
>Overwrite the element `true` to `1` in the above list __l__

In [1290]:
print(f"old list: \n{l}")

l[l.index('true')] = 1
l

old list: 
[0, 'robot', -9, False, 77, 77, 100, 'true']


[0, 'robot', -9, False, 77, 77, 100, 1]

>__Task 9__
>
>Add `age` and `weight` to the list __e__ below using __`+`__

In [1291]:
e = ['diabetes', 'heart bypass']
e

['diabetes', 'heart bypass']

In [1292]:
f = e + ['age', 'weight']
f

['diabetes', 'heart bypass', 'age', 'weight']

Alternatively, you can use the __`extend()`__ method to add item(s) to the end of the list:

In [1293]:
e.extend(['age', 'weight'])
e

['diabetes', 'heart bypass', 'age', 'weight']

### Dictionaries

In [1294]:
cities = {'Australia' :['Sydney', 'Melbourne', 'Canberra'],
          'Canada'    :['Toronto', 'Montreal', 'Ottawa'],
          'Germany'   :['Berlin', 'Hamburg', 'Munich'],
          'Japan'     :['Tokyo', 'Osaka', 'Nagoya']}
cities

{'Australia': ['Sydney', 'Melbourne', 'Canberra'],
 'Canada': ['Toronto', 'Montreal', 'Ottawa'],
 'Germany': ['Berlin', 'Hamburg', 'Munich'],
 'Japan': ['Tokyo', 'Osaka', 'Nagoya']}

>__Task 10__
>
>Return only values of the `Japan` key

In [1295]:
task_10 = cities['Japan']
print(task_10)

['Tokyo', 'Osaka', 'Nagoya']


>__Task 11__
>
>Return only values and only keys of the dictionary __cities__

In [1296]:
# Return only values
# # First way
# for country in cities:
#     print(cities.values())
# # Second way
print(cities.values())
# # Third way
# task_11 = [city for country in cities.values() for city in country]
# print(task_11)

dict_values([['Sydney', 'Melbourne', 'Canberra'], ['Toronto', 'Montreal', 'Ottawa'], ['Berlin', 'Hamburg', 'Munich'], ['Tokyo', 'Osaka', 'Nagoya']])


In [1297]:
# Return only keys
# # First way
# for country in cities:
#     print(country)
# # Second way
# print(cities.keys())
# # Third way
task_12 = [country for country in cities.keys()]
print(task_12)

['Australia', 'Canada', 'Germany', 'Japan']


You can use a __`for`__ loop to print not only keys but also the values corresponding to that keys:

In [1298]:
for k in cities.keys():
    print('key: ', k, '\nvalue: ', cities[k], '\n')

key:  Australia 
value:  ['Sydney', 'Melbourne', 'Canberra'] 

key:  Canada 
value:  ['Toronto', 'Montreal', 'Ottawa'] 

key:  Germany 
value:  ['Berlin', 'Hamburg', 'Munich'] 

key:  Japan 
value:  ['Tokyo', 'Osaka', 'Nagoya'] 



>__Task 12__
>
>Return the same output above using the __`items()`__ method within a `for` loop

In [1299]:
for k, v in cities.items():
    print(f"key: {k} \nvalue: {v}\n")

key: Australia 
value: ['Sydney', 'Melbourne', 'Canberra']

key: Canada 
value: ['Toronto', 'Montreal', 'Ottawa']

key: Germany 
value: ['Berlin', 'Hamburg', 'Munich']

key: Japan 
value: ['Tokyo', 'Osaka', 'Nagoya']



>__Task 13__
>
>Add `Egypt` as a new key to __cities__ and `Cairo`, `Durban`, `Alexandria` as its corresponding values

In [1300]:
cities['Egypt'] = ['Cairo', 'Durban', 'Alexandria']
cities

{'Australia': ['Sydney', 'Melbourne', 'Canberra'],
 'Canada': ['Toronto', 'Montreal', 'Ottawa'],
 'Germany': ['Berlin', 'Hamburg', 'Munich'],
 'Japan': ['Tokyo', 'Osaka', 'Nagoya'],
 'Egypt': ['Cairo', 'Durban', 'Alexandria']}

>__Task 14__
>
>`Durban` is actually in South Africa. Overwrite it with `Giza` and then confirm values of the __Egypt__ column

In [1301]:
Durban_index = cities['Egypt'].index('Durban')
cities['Egypt'][Durban_index] = 'Giza'
# cities['Egypt'][1] = 'Giza' 
cities

{'Australia': ['Sydney', 'Melbourne', 'Canberra'],
 'Canada': ['Toronto', 'Montreal', 'Ottawa'],
 'Germany': ['Berlin', 'Hamburg', 'Munich'],
 'Japan': ['Tokyo', 'Osaka', 'Nagoya'],
 'Egypt': ['Cairo', 'Giza', 'Alexandria']}

>__Task 15__
>
>Delete the key `Germany` from __cities__ 

In [1302]:
# del cities['Germany']
cities.pop('Germany')
cities

{'Australia': ['Sydney', 'Melbourne', 'Canberra'],
 'Canada': ['Toronto', 'Montreal', 'Ottawa'],
 'Japan': ['Tokyo', 'Osaka', 'Nagoya'],
 'Egypt': ['Cairo', 'Giza', 'Alexandria']}

## NumPy Arrays

>__Task 16__
>
>Create an array that contains a list of `99`, `2`, `65`

In [1303]:
arr = np.array([99,2,65])
arr

array([99,  2, 65])

>__Task 17__
>
>Run the following operations to see the results

In [1304]:
# Natural logarithm
np.log(arr)

array([4.59511985, 0.69314718, 4.17438727])

In [1305]:
# Square root
np.sqrt(arr)

array([9.94987437, 1.41421356, 8.06225775])

In [1306]:
# Cosine
np.cos(arr)


array([ 0.03982088, -0.41614684, -0.56245385])

We can use the __`arange()`__ method to create an array from 0 to any number of values we want. For example, we want an array of 20 numbers, we write:

In [1307]:
num1 = np.arange(20)
num1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

>__Task 18__
>
>Retrieve the first 5 numbers of the above array __num1__

In [1308]:
print(num1[:5])
# task_18 = num1[:5]
# task_18

[0 1 2 3 4]


We can also pass the __`reshape()`__ function with `arange()` to specify rows and columns. For example, we can rearrange the above array into 5 rows and 4 columns:

In [1309]:
num2 = np.arange(20).reshape(5,4)
num2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

>__Task 19__
>
>Retrieve the numbers from the last 2 rows and first 3 columns in the array __num2__ (your output should return `[12, 13, 14], [16, 17, 18]`)

In [1310]:
task_19 = num2[-2:, :3]
task_19

array([[12, 13, 14],
       [16, 17, 18]])

## Pandas Series and DataFrames

>__Task 20__
>
>Import the data file "bank_data.csv"

In [1311]:
import pandas as pd

bank = pd.read_csv('bank_data.csv')
bank

age            job  marital  education default  balance housing loan  \
0     30.0     unemployed  married    primary      no   1787.0      no   no   
1     33.0       services  married  secondary      no   4789.0     yes  yes   
2     35.0     management   single   tertiary      no   1350.0     yes   no   
3     30.0     management  married   tertiary      no      NaN     yes  yes   
4     59.0    blue-collar  married  secondary      no      0.0     yes   no   
...    ...            ...      ...        ...     ...      ...     ...  ...   
4516  33.0       services  married  secondary      no   -333.0     yes   no   
4517  57.0  self-employed  married   tertiary     yes  -3313.0     yes  yes   
4518  57.0     technician  married  secondary      no    295.0      no   no   
4519  28.0    blue-collar  married  secondary      no   1137.0      no   no   
4520  44.0   entrepreneur   single   tertiary      no   1136.0     yes  yes   

       contact   day  month  duration  campaign  pdays  previous poutcome   y  \
0     cellular  19.0     10      79.0       1.0   -1.0       0.0  unknown  no   
1     cellular  11.0      5     220.0       1.0  339.0       4.0  failure  no   
2     cellular  16.0      4     185.0       1.0  330.0       1.0  failure  no   
3          NaN   3.0      6     199.0       4.0   -1.0       0.0  unknown  no   
4          NaN   5.0      5     226.0       1.0   -1.0       0.0  unknown  no   
...        ...   ...    ...       ...       ...    ...       ...      ...  ..   
4516  cellular  30.0      7     329.0       5.0   -1.0       0.0  unknown  no   
4517       NaN   9.0      5     153.0       1.0   -1.0       0.0  unknown  no   
4518  cellular  19.0      8     151.0      11.0   -1.0       0.0  unknown  no   
4519  cellular   6.0      2     129.0       4.0  211.0       3.0    other  no   
4520  cellular   3.0      4     345.0       2.0  249.0       7.0    other  no   

      year  
0     2022  
1     2022  
2     2022  
3     2022  
4     2022  
...    ...  
4516  2022  
4517  2022  
4518  2022  
4519  2022  
4520  2022  

[4521 rows x 18 columns]

>__Task 21__
>
>Select __age__ column as a series and confirm the result by checking its data type

In [1312]:
age_series = bank['age']
age_series
print(type(age_series))

<class 'pandas.core.series.Series'>


In [1313]:
# Return data type
print(age_series.dtype)

float64


Notice that __`df[...]` returns a series and `df[[...]]` returns a data frame__.

>__Task 22__
>
>Select columns __job__, __education__, and __balance__ as a data frame and confirm the result by checking its data type

In [1314]:
task_22 = bank[['age', 'education', 'balance']]
task_22

age  education  balance
0     30.0    primary   1787.0
1     33.0  secondary   4789.0
2     35.0   tertiary   1350.0
3     30.0   tertiary      NaN
4     59.0  secondary      0.0
...    ...        ...      ...
4516  33.0  secondary   -333.0
4517  57.0   tertiary  -3313.0
4518  57.0  secondary    295.0
4519  28.0  secondary   1137.0
4520  44.0   tertiary   1136.0

[4521 rows x 3 columns]

In [1315]:
# Return data type
print(f"==> Data type of whole: \n{type(task_22)}\n")
print(f"==> Data type of all individual columns: \n{task_22.dtypes}\n")

==> Data type of whole: 
<class 'pandas.core.frame.DataFrame'>

==> Data type of all individual columns: 
age          float64
education     object
balance      float64
dtype: object



>__Task 23__
>
>Retrieve the last 7 rows and first 5 columns from the __bank__ data

In [1316]:
# last 7 rows, first 5 columns
task_23 = bank.iloc[-7:, :5] 
print(task_23)


       age            job  marital  education default
4514  38.0    blue-collar  married  secondary      no
4515  32.0       services   single  secondary      no
4516  33.0       services  married  secondary      no
4517  57.0  self-employed  married   tertiary     yes
4518  57.0     technician  married  secondary      no
4519  28.0    blue-collar  married  secondary      no
4520  44.0   entrepreneur   single   tertiary      no


### Dates and Times

Let's create a new column of the client contact dates using the __bank__ data:

In [1317]:
bank['contact_date'] = bank['year'].astype(str)+'-'+bank['month'].astype(str)+'-'+bank['day'].astype(int).astype(str)
bank['contact_date']

0       2022-10-19
1        2022-5-11
2        2022-4-16
3         2022-6-3
4         2022-5-5
           ...    
4516     2022-7-30
4517      2022-5-9
4518     2022-8-19
4519      2022-2-6
4520      2022-4-3
Name: contact_date, Length: 4521, dtype: object

The last line above shows that the dtype (data type) is a generic object, not a datetime type.

>__Task 24__
>
>Convert the __contact_date__ column to a datetime object

In [1318]:
bank['contact_date'] = pd.to_datetime(bank[['year','month','day']])
bank['contact_date']

0      2022-10-19
1      2022-05-11
2      2022-04-16
3      2022-06-03
4      2022-05-05
          ...    
4516   2022-07-30
4517   2022-05-09
4518   2022-08-19
4519   2022-02-06
4520   2022-04-03
Name: contact_date, Length: 4521, dtype: datetime64[ns]

Now, it is properly read as date.

## Data Manipulation

In [1319]:
import warnings
warnings.filterwarnings("ignore")

>__Task 25__
>
>Import the data file "hc_train.csv" and explore the first 5 rows

In [1320]:
hc = pd.read_csv('hc_train.csv')
hc.head()

Unnamed: 0  case_id  Hospital_code Hospital_type_code  City_Code_Hospital  \
0      119967   119968             27                  a                   7   
1       92433    92434              6                  a                   6   
2      132258   132259             16                  c                   3   
3      168439   168440             23                  a                   6   
4       82100    82101             25                  e                   1   

  Hospital_region_code  Available Extra Rooms in Hospital  Department  \
0                    Y                                  3  gynecology   
1                    X                                  4  gynecology   
2                    Z                                  4  gynecology   
3                    X                                  2  anesthesia   
4                    X                                  3  gynecology   

  Ward_Type Ward_Facility_Code  Bed Grade  patientid  City_Code_Patient  \
0         R                  C        2.0      11389                8.0   
1         Q                  F        1.0      12522                2.0   
2         S                  A        3.0     119556                8.0   
3         S                  F        3.0     107177                8.0   
4         R                  E        3.0      64508               13.0   

  Type of Admission Severity of Illness  Visitors with Patient    Age  \
0         Emergency               Minor                      2  11-20   
1         Emergency             Extreme                      4  31-40   
2            Trauma            Moderate                      6  71-80   
3            Urgent             Extreme                      2  71-80   
4            Trauma            Moderate                      3  61-70   

   Admission_Deposit                Stay  
0             5072.0               21-30  
1             3585.0               21-30  
2             4013.0  More than 100 Days  
3             5160.0               21-30  
4             4099.0               21-30

>__Task 26__
>
>Convert the values of the __Department__ column to uppercase

In [1321]:
hc['Department'] = hc['Department'].str.upper()
hc.head()

Unnamed: 0  case_id  Hospital_code Hospital_type_code  City_Code_Hospital  \
0      119967   119968             27                  a                   7   
1       92433    92434              6                  a                   6   
2      132258   132259             16                  c                   3   
3      168439   168440             23                  a                   6   
4       82100    82101             25                  e                   1   

  Hospital_region_code  Available Extra Rooms in Hospital  Department  \
0                    Y                                  3  GYNECOLOGY   
1                    X                                  4  GYNECOLOGY   
2                    Z                                  4  GYNECOLOGY   
3                    X                                  2  ANESTHESIA   
4                    X                                  3  GYNECOLOGY   

  Ward_Type Ward_Facility_Code  Bed Grade  patientid  City_Code_Patient  \
0         R                  C        2.0      11389                8.0   
1         Q                  F        1.0      12522                2.0   
2         S                  A        3.0     119556                8.0   
3         S                  F        3.0     107177                8.0   
4         R                  E        3.0      64508               13.0   

  Type of Admission Severity of Illness  Visitors with Patient    Age  \
0         Emergency               Minor                      2  11-20   
1         Emergency             Extreme                      4  31-40   
2            Trauma            Moderate                      6  71-80   
3            Urgent             Extreme                      2  71-80   
4            Trauma            Moderate                      3  61-70   

   Admission_Deposit                Stay  
0             5072.0               21-30  
1             3585.0               21-30  
2             4013.0  More than 100 Days  
3             5160.0               21-30  
4             4099.0               21-30

### Replace Values

>__Task 27__
>
>Replace `TB & Chest disease` in the __Department__ column with `Tuberculosis & Chest`

In [1322]:
hc['Department'].unique()

array(['GYNECOLOGY', 'ANESTHESIA', 'RADIOTHERAPY', 'SURGERY',
       'TB & CHEST DISEASE'], dtype=object)

In [1323]:

hc['Department'] = hc['Department'].str.replace('TB & Chest disease'.upper(), 'Tuberculosis & Chest'.upper())
# Print unique variables in the column to confirm the change 
hc['Department'].unique()

array(['GYNECOLOGY', 'ANESTHESIA', 'RADIOTHERAPY', 'SURGERY',
       'TUBERCULOSIS & CHEST'], dtype=object)

We can also replace with different values by passing a list or dict as substitutes.

>__Task 28__
>
>Replace values in the __Severity of Illness__ column with a dictionary that maps variables below:
>
>- Extreme: '3rd degree'
>- Moderate: '2nd degree'
>- Minor: '1st degree'

In [1324]:
# list(hc.columns)
hc['Severity of Illness'].unique()

array(['Minor', 'Extreme', 'Moderate'], dtype=object)

In [1325]:
# Create a dict
map_dict = {
    'Extreme': '3rd degree',
    'Moderate': '2nd degree',
    'Minor': '1st degree'
    }
# Replace values with the dict
# hc['Severity of Illness'] = hc['Severity of Illness'].map(map_dict)   # changes all values, non-matching keys become NaN
hc['Severity of Illness'] = hc['Severity of Illness'].replace(map_dict) # only changes matching keys

hc['Severity of Illness'].unique()
# hc['Severity of Illness']


array(['1st degree', '3rd degree', '2nd degree'], dtype=object)

### Rename Column and Row Labels

>__Task 29__
>
>Rename all column headings to their lowercase values by passing a `str` function

In [1326]:
hc.columns = hc.columns.str.lower()
hc.columns


Index(['unnamed: 0', 'case_id', 'hospital_code', 'hospital_type_code',
       'city_code_hospital', 'hospital_region_code',
       'available extra rooms in hospital', 'department', 'ward_type',
       'ward_facility_code', 'bed grade', 'patientid', 'city_code_patient',
       'type of admission', 'severity of illness', 'visitors with patient',
       'age', 'admission_deposit', 'stay'],
      dtype='object')

>__Task 30__
>
>Rename the column headings below using a dictionary that maps
>
>- `Severity of Illness` to `Severity`
>- `case_id` to `ID`

In [1327]:
col_dict = {
    'severity of illness': 'Severity',
    'case_id': 'ID'
    }
hc = hc.rename(columns=col_dict)
hc.columns

Index(['unnamed: 0', 'ID', 'hospital_code', 'hospital_type_code',
       'city_code_hospital', 'hospital_region_code',
       'available extra rooms in hospital', 'department', 'ward_type',
       'ward_facility_code', 'bed grade', 'patientid', 'city_code_patient',
       'type of admission', 'Severity', 'visitors with patient', 'age',
       'admission_deposit', 'stay'],
      dtype='object')

### Binning Methods

>__Task 31__
>
>Group the case IDs into three categories below:
>
>- (0, 100000) to `old case`
>- (100001-200000) to `recent case`
>- (200001-last) to `new case`

In [1328]:
# Check the maximum value of the column
hc['ID'].max()

np.int64(318438)

In [1329]:
bins = [0, 100000, 200000, float('inf')]
labels = ['old case', 'recent case', 'new case']

group = pd.cut(hc['ID'], bins=bins, labels=labels, include_lowest=True)
print(group.head())
group

0    recent case
1       old case
2    recent case
3    recent case
4       old case
Name: ID, dtype: category
Categories (3, object): ['old case' < 'recent case' < 'new case']


0        recent case
1           old case
2        recent case
3        recent case
4           old case
            ...     
51233       new case
51234       new case
51235       old case
51236    recent case
51237       new case
Name: ID, Length: 51238, dtype: category
Categories (3, object): ['old case' < 'recent case' < 'new case']

>__Task 32__
>
>Group the case IDs into to 3 equal-sized bins with 4 decimal places

In [1330]:
group_equ = pd.cut(hc['ID'], bins=3, precision=4)
print(group_equ.head())
group_equ

0    (106146.6667, 212292.3333]
1       (-317.437, 106146.6667]
2    (106146.6667, 212292.3333]
3    (106146.6667, 212292.3333]
4       (-317.437, 106146.6667]
Name: ID, dtype: category
Categories (3, interval[float64, right]): [(-317.437, 106146.6667] < (106146.6667, 212292.3333] < (212292.3333, 318438.0]]


0        (106146.6667, 212292.3333]
1           (-317.437, 106146.6667]
2        (106146.6667, 212292.3333]
3        (106146.6667, 212292.3333]
4           (-317.437, 106146.6667]
                    ...            
51233       (212292.3333, 318438.0]
51234       (212292.3333, 318438.0]
51235       (-317.437, 106146.6667]
51236    (106146.6667, 212292.3333]
51237    (106146.6667, 212292.3333]
Name: ID, Length: 51238, dtype: category
Categories (3, interval[float64, right]): [(-317.437, 106146.6667] < (106146.6667, 212292.3333] < (212292.3333, 318438.0]]

>__Task 33__
>
>Group the case IDs into 4 quartiles with 2 decimal places

In [1331]:
group_qua = pd.qcut(hc['ID'], q=4, precision=2)
group_qua

0        (79834.25, 159728.5]
1        (79834.25, 159728.5]
2        (79834.25, 159728.5]
3        (159728.5, 238968.5]
4        (79834.25, 159728.5]
                 ...         
51233    (238968.5, 318438.0]
51234    (238968.5, 318438.0]
51235        (0.99, 79834.25]
51236    (79834.25, 159728.5]
51237    (159728.5, 238968.5]
Name: ID, Length: 51238, dtype: category
Categories (4, interval[float64, right]): [(0.99, 79834.25] < (79834.25, 159728.5] < (159728.5, 238968.5] < (238968.5, 318438.0]]

### Random Sampling

>__Task 34__
>
>Randomly select 10 data points from the __hc__ data without repeat elements

In [1332]:
task_34 = hc.sample(n=10, replace=False)
task_34

unnamed: 0      ID  hospital_code hospital_type_code  \
6089       217230  217231             18                  d   
8861        95205   95206             15                  c   
30262       51394   51395             29                  a   
36566      288453  288454             23                  a   
17675      202128  202129             23                  a   
22733       62650   62651              6                  a   
43235       51920   51921             26                  b   
17696      230337  230338             25                  e   
6545       220492  220493             26                  b   
2743       227982  227983              2                  c   

       city_code_hospital hospital_region_code  \
6089                   13                    Y   
8861                    5                    Z   
30262                   4                    X   
36566                   6                    X   
17675                   6                    X   
22733                   6                    X   
43235                   2                    Y   
17696                   1                    X   
6545                    2                    Y   
2743                    5                    Z   

       available extra rooms in hospital    department ward_type  \
6089                                   4    GYNECOLOGY         Q   
8861                                   6    GYNECOLOGY         Q   
30262                                  3    GYNECOLOGY         S   
36566                                  4    GYNECOLOGY         R   
17675                                  4    GYNECOLOGY         Q   
22733                                  4    GYNECOLOGY         Q   
43235                                  5  RADIOTHERAPY         S   
17696                                  4    GYNECOLOGY         R   
6545                                   4    GYNECOLOGY         Q   
2743                                   4    GYNECOLOGY         Q   

      ward_facility_code  bed grade  patientid  city_code_patient  \
6089                   B        2.0      15599                8.0   
8861                   F        3.0      93915                5.0   
30262                  F        4.0      25131                2.0   
36566                  F        2.0      17582                4.0   
17675                  F        1.0      82953                2.0   
22733                  F        3.0      78543                8.0   
43235                  D        4.0      24315                8.0   
17696                  E        2.0      36929                1.0   
6545                   D        3.0      44930                8.0   
2743                   F        4.0      14715               21.0   

      type of admission    Severity  visitors with patient    age  \
6089             Trauma  2nd degree                      4  41-50   
8861             Trauma  3rd degree                      4  71-80   
30262         Emergency  1st degree                      4  31-40   
36566         Emergency  1st degree                      2  21-30   
17675            Trauma  1st degree                      2  51-60   
22733            Trauma  2nd degree                      2  31-40   
43235            Trauma  1st degree                      4  31-40   
17696         Emergency  2nd degree                      3  41-50   
6545             Trauma  3rd degree                      6  51-60   
2743          Emergency  2nd degree                      2  41-50   

       admission_deposit                stay  
6089              4295.0               31-40  
8861              4713.0               31-40  
30262             4051.0  More than 100 Days  
36566             5733.0               21-30  
17675             4400.0               11-20  
22733             4297.0               21-30  
43235             5740.0               21-30  
17696             4699.0                0-10  
6545              4450.0               71-80  
2743              6152.

>__Task 35__
>
>Randomly select 50 data points from the __patientid__ column allowing repeat elements

In [1333]:
task_35 = hc['patientid'].sample(n=50, replace=True)
task_35

24024    100767
41888     80448
22923     34584
8375      82303
3981      24906
7601     123804
48958     39548
13597     18006
30200    106896
1198     130173
47034     83812
30867     85342
33260     24522
42539    125030
22869    130795
7628     121449
43027     40531
19405    117779
26979     57518
22174     41577
11076     17542
47483     53704
46041      3853
864       64869
18045     59502
19639     55868
44931    117833
44712     65572
24363    106434
27078     22687
14471     88275
32427    116288
17014     88250
23176     42499
26351     56572
24898     13287
5463      69243
48480     11259
27122     79669
19213     42438
25796     58039
16527     78234
23736     69301
43672    128647
12439     20443
26119    118829
4590      80521
45771      8585
19635    101828
2949      51786
Name: patientid, dtype: int64